### ISSUE TITLE
Text when no post found

### ISSUE THREAD

**Issue by hmaegaard** [aldolat/posts-in-sidebar#14]
A blank field will result in that the widget will not be displayed, even if posts should be found. Entering a blank works as workaround.

**Comment by aldolat** [comment]
The user must enter something in the field, otherwise the widget won't be displayed, even if there are posts. It's by design. 

If the user doesn't want to display the widget at all if no posts are found, he can leave the field blank and the widget will not be displayed. 

Perhaps this behavior is not as simple as I would, so I will change this adding a checkbox.

**Comment by aldolat** [comment]
Added the checkbox and removed old function.
